# Generated by Django 5.1.6 on 2025-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=5)),
                ('student_section', models.CharField(max_length=2)),
                ('student_age', models.CharField(max_length=2)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('student_phone', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_address', models.TextField()),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_relation', models.CharField(max_length=10)),
                ('parent_email', models.EmailField(max_length=254, unique=True)),
                ('parent_address', models.TextField()),
                ('parent_phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
