# Generated by Django 5.1.6 on 2025-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_age', models.CharField(max_length=2)),
                ('worker_department', models.CharField(max_length=50)),
                ('worker_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('worker_phone', models.CharField(max_length=15)),
                ('worker_email', models.EmailField(max_length=254, unique=True)),
                ('worker_address', models.TextField()),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
