# Generated by Django 5.1.6 on 2025-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_qr_code_worker_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_photo',
            field=models.ImageField(upload_to='worker_photos/'),
        ),
    ]
