# Generated by Django 5.1.6 on 2025-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_student_user_remove_worker_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
