# Generated by Django 5.1.6 on 2025-04-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_student_password_alter_worker_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='worker_email',
            new_name='email',
        ),
    ]
