# Generated by Django 5.1.6 on 2025-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bookcheckout_delete_user_student_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('late_entry', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
