# Generated by Django 5.1.6 on 2025-04-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckout',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
