# Generated by Django 5.1.6 on 2025-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bookcheckout_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckout',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
