# Generated by Django 5.1.6 on 2025-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookcheckout_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcheckout',
            name='checkout_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
