# Generated by Django 5.1.6 on 2025-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_bookcheckout_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='location',
            field=models.CharField(choices=[('main_gate', 'Main Gate'), ('library', 'Library Entrance'), ('gym', 'Gym Entrance'), ('auditorium', 'Auditorium')], default='main_gate', max_length=20),
        ),
    ]
